version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2
  node: circleci/node@7.1.0

executors:
  base:
    docker:
      - image: cimg/base:current
    working_directory: ~/project
  php:
    docker:
      - image: cimg/php:8.2-node
    working_directory: ~/project

commands:
  set_version_variable:
    description: "Set the VERSION environment variable"
    steps:
      - run:
          command: |
            echo "export VERSION=$(awk '$2 == "Version:" {print $3}' ~/project/genesis-simple-menus/simple-menu.php)" >> ${BASH_ENV}
            source ${BASH_ENV}
            echo "VERSION set to: ${VERSION}"

  create_zip_artifacts:
    description: "Create zip artifacts for WP.org (for testing) and WPE (manual deployment)"
    steps:
      - node/install
      - node/install-packages:
          app-dir: ~/project/genesis-simple-menus
          override-ci-command: npm install
      - run:
          name: Install WP-CLI
          command: |
            echo "Installing WP-CLI..."
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
            wp --info
      - run:
          name: Create zips and info.json
          command: |
            cd ~/project/genesis-simple-menus
            echo "Node.js version: $(node --version)"
            echo "npm version: $(npm --version)"
            npm run zip:all
      - store_artifacts:
          path: ~/project/genesis-simple-menus/artifacts
          destination: artifacts

jobs:
  checkout:
    executor: base
    steps:
      - checkout:
          path: genesis-simple-menus
      - persist_to_workspace:
          root: ~/project
          paths:
            - genesis-simple-menus

  checks:
    executor: php
    steps:
      - attach_workspace:
          at: ~/project
      - set_version_variable
      - run:
          name: Run phpcs
          command: |
            cd ~/project/genesis-simple-menus
            echo "Composer version: $(composer --version)"
            composer install
            composer phpcs

  create_artifacts:
    executor: php
    steps:
      - attach_workspace:
          at: ~/project
      - create_zip_artifacts

  svn_dry_run:
    executor: base
    steps:
      - attach_workspace:
          at: ~/project
      - wp-svn/deploy-plugin:
          plugin-path: genesis-simple-menus
          dry-run: true

  deploy:
    executor: base
    steps:
      - attach_workspace:
          at: ~/project
      - wp-svn/deploy-plugin:
          plugin-path: genesis-simple-menus

workflows:
  version: 2
  test-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - master
      - checks:
          requires:
            - checkout
          filters:
            branches:
              ignore:
                - master
      - create_artifacts:
          requires:
            - checkout
          filters:
            branches:
              ignore:
                - master
      - svn_dry_run:
          requires:
            - checks
          filters:
            branches:
              ignore:
                - master
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - checks
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump

  branch_deploy:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
      - checks:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
      - create_artifacts:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
      - deploy:
          context: genesis-svn
          requires:
            - checks
          filters:
            branches:
              only:
                - master

  tag_deploy:
    jobs:
      - checkout:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - checks:
          requires:
            - checkout
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - create_artifacts:
          requires:
            - checkout
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - wp-svn/check-versions:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy:
          context: genesis-svn
          requires:
            - checks
            - wp-svn/check-versions
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
